<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ddt4All.Core\Ddt4All.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <!-- shared synthetic data generators -->
    <Compile Include="..\Ddt4All.Core.Tests\Synthetic\*.cs" Link="Synthetic\%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
