using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Text.Json;
using Ddt4All.App.Services;

namespace Ddt4All.App.Localization;

public sealed record LanguageInfo(string Code, string NativeName, string EnglishName)
{
    public override string ToString() => NativeName;
}

/// <summary>
/// Runtime localisation. Keys are the English source strings (same msgids as the Python gettext catalogs),
/// so a missing translation falls back to the key. Catalogs are flat JSON files embedded in the assembly
/// (generated by tools/po2json.py) and parsed lazily, only for the active language, with the source-generated
/// JSON serializer.
/// </summary>
public sealed class Loc
{
    public static Loc Instance { get; } = new();

    public const string SystemCode = "system";

    public static readonly IReadOnlyList<LanguageInfo> Languages =
    [
        new("en", "English", "English"),
        new("de", "Deutsch", "German"),
        new("es", "Español", "Spanish"),
        new("fr", "Français", "French"),
        new("hu", "Magyar", "Hungarian"),
        new("it", "Italiano", "Italian"),
        new("nl", "Nederlands", "Dutch"),
        new("pl", "Polski", "Polish"),
        new("pt", "Português", "Portuguese"),
        new("ro", "Română", "Romanian"),
        new("ru", "Русский", "Russian"),
        new("sr", "Српски", "Serbian"),
        new("cs-CZ", "Čeština", "Czech"),
        new("tr", "Türkçe", "Turkish"),
        new("uk-UA", "Українська", "Ukrainian"),
    ];

    private readonly Dictionary<string, TrItem> _items = new();
    private Dictionary<string, string>? _map;

    /// <summary>Effective language code currently loaded ("en" when none).</summary>
    public string Language { get; private set; } = "en";
    public event Action? LanguageChanged;

    public static string T(string key) => Instance.Translate(key);
    public static string F(string key, params object?[] args) => string.Format(CultureInfo.CurrentCulture, Instance.Translate(key), args);

    public string Translate(string key) =>
        _map is not null && _map.TryGetValue(key, out var v) && v.Length > 0 ? v : key;

    internal TrItem GetItem(string key)
    {
        if (!_items.TryGetValue(key, out var item))
            _items[key] = item = new TrItem(this, key);
        return item;
    }

    /// <summary>Resolve "system" or a code to a supported language code.</summary>
    public static string Resolve(string? code)
    {
        if (string.IsNullOrEmpty(code) || code == SystemCode)
            code = CultureInfo.CurrentUICulture.Name; // e.g. fr-FR, cs-CZ
        code = code.Replace('_', '-');
        foreach (var l in Languages)
            if (string.Equals(l.Code, code, StringComparison.OrdinalIgnoreCase)) return l.Code;
        var neutral = code.Split('-')[0];
        foreach (var l in Languages)
            if (string.Equals(l.Code.Split('-')[0], neutral, StringComparison.OrdinalIgnoreCase)) return l.Code;
        return "en";
    }

    public void SetLanguage(string? code)
    {
        var resolved = Resolve(code);
        if (resolved == Language && (_map is not null || resolved == "en")) return;
        _map = resolved == "en" ? null : LoadCatalog(resolved);
        Language = resolved;
        try { CultureInfo.CurrentUICulture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo(resolved); } catch (CultureNotFoundException) { }
        foreach (var item in _items.Values) item.Refresh();
        LanguageChanged?.Invoke();
    }

    private static Dictionary<string, string>? LoadCatalog(string code)
    {
        using var s = typeof(Loc).Assembly.GetManifestResourceStream($"Ddt4All.App.Locales.{code}.json");
        if (s is null) return null;
        return JsonSerializer.Deserialize(s, LocaleJsonContext.Default.DictionaryStringString);
    }

    internal sealed class TrItem : INotifyPropertyChanged
    {
        private readonly Loc _loc;
        private readonly string _key;
        public TrItem(Loc loc, string key) { _loc = loc; _key = key; }
        public string Value => _loc.Translate(_key);
        public event PropertyChangedEventHandler? PropertyChanged;
        public void Refresh() => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Value)));
    }
}
