<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ddt4All.Plugins</RootNamespace>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ddt4All.Core\Ddt4All.Core.csproj" />
    <ProjectReference Include="..\Ddt4All.Comms\Ddt4All.Comms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ddt4All.Plugins.Tests" />
  </ItemGroup>

</Project>
